"""Votes column added

Revision ID: a6b10d2d1984
Revises: 
Create Date: 2020-09-21 22:04:58.871644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b10d2d1984'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('omp', sa.Column('votes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('omp', 'votes')
    # ### end Alembic commands ###
